using System.Collections.Generic;

namespace WarCraftLibrary
{
    public static class AnimationDatabase
    {
        private static readonly Dictionary<string, AnimationConfig> _configs =
            new Dictionary<string, AnimationConfig>
            {
                // =================== PEASANT =====================
                ["Peasant_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Move_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Move_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Move_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Move_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["Peasant_Idle_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Idle_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Idle_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Idle_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Idle_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Idle_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Idle_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Idle_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["Peasant_Attack_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Attack_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Attack_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Attack_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peasant_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Peasant_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Peasant_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Peasant_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                // ✅ DEATH: Corpse displays for 30 seconds then clears
                ["Peasant_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = false },
                ["Peasant_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = false },
                ["Peasant_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = false },
                ["Peasant_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = false },
                ["Peasant_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = false },
                ["Peasant_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = false },
                ["Peasant_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = false },
                ["Peasant_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = false },

                // ==================== PEON =======================
                ["Peon_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Move_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Move_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Move_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Move_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["Peon_Idle_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Idle_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Idle_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Idle_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Idle_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Idle_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Idle_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Idle_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["Peon_Attack_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Attack_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Attack_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Attack_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Peon_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Peon_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Peon_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Peon_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Peon_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Peon_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Peon_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Peon_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Peon_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Peon_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Peon_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Peon_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },

                // =================== FOOTMAN =====================
                ["Footman_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Footman_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Footman_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Footman_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Footman_Move_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Footman_Move_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Footman_Move_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Footman_Move_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },

                ["Footman_Idle_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 8, Loop = true },
                ["Footman_Idle_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 8, Loop = true },
                ["Footman_Idle_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 8, Loop = true },
                ["Footman_Idle_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 8, Loop = true },
                ["Footman_Idle_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 8, Loop = true },
                ["Footman_Idle_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 8, Loop = true },
                ["Footman_Idle_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 8, Loop = true },
                ["Footman_Idle_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 8, Loop = true },

                ["Footman_Attack_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Footman_Attack_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Footman_Attack_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Footman_Attack_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Footman_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Footman_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Footman_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Footman_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Footman_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Footman_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Footman_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Footman_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Footman_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Footman_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Footman_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Footman_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                // =================== GRUNT =====================
                ["Grunt_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Move_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Grunt_Move_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Grunt_Move_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Grunt_Move_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },

                ["Grunt_Idle_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Idle_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Idle_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Idle_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Idle_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Idle_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Idle_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Idle_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["Grunt_Attack_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Attack_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Attack_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Attack_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Grunt_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Grunt_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Grunt_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Grunt_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Grunt_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Grunt_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Grunt_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Grunt_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Grunt_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Grunt_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Grunt_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Grunt_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },

                // =================== ARCHER =====================
                ["Archer_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Move_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Archer_Move_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Archer_Move_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Archer_Move_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },

                ["Archer_Idle_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Idle_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Idle_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Idle_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Idle_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Idle_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Idle_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Idle_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["Archer_Attack_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Attack_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Attack_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Attack_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Archer_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Archer_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Archer_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Archer_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Archer_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Archer_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Archer_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Archer_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Archer_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Archer_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Archer_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Archer_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },

                // =================== TROLL AXE THROWER =====================
                ["TrollAxeThrower_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Move_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Move_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Move_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Move_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },

                ["TrollAxeThrower_Idle_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Idle_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Idle_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Idle_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Idle_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Idle_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Idle_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Idle_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["TrollAxeThrower_Attack_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Attack_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Attack_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Attack_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["TrollAxeThrower_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["TrollAxeThrower_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["TrollAxeThrower_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["TrollAxeThrower_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["TrollAxeThrower_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["TrollAxeThrower_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["TrollAxeThrower_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["TrollAxeThrower_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["TrollAxeThrower_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["TrollAxeThrower_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["TrollAxeThrower_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["TrollAxeThrower_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },

                // =================== BRIGAND =====================
                ["Brigand_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Move_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Brigand_Move_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Brigand_Move_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Brigand_Move_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },

                ["Brigand_Idle_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Idle_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Idle_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Idle_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Idle_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Idle_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Idle_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Idle_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["Brigand_Attack_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Attack_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Attack_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Attack_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Brigand_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Brigand_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Brigand_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Brigand_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Brigand_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Brigand_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Brigand_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Brigand_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Brigand_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Brigand_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Brigand_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Brigand_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },

                // =================== OGRE =====================
                ["Ogre_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Move_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Ogre_Move_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Ogre_Move_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },
                ["Ogre_Move_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = true },

                ["Ogre_Idle_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Idle_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Idle_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Idle_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Idle_NE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Idle_NW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Idle_SE"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Idle_SW"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },

                ["Ogre_Attack_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Attack_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Attack_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Attack_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Ogre_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Ogre_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Ogre_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Ogre_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Ogre_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Ogre_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Ogre_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Ogre_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Ogre_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Ogre_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Ogre_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Ogre_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },

                // =================== CLERIC =====================
                ["Cleric_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Cleric_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Cleric_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Cleric_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Cleric_Move_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Move_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Move_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Move_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Cleric_Idle_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Idle_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Idle_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Idle_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Idle_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Idle_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Idle_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Idle_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Cleric_Attack_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Attack_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Attack_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Attack_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cleric_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Cleric_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cleric_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cleric_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cleric_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cleric_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cleric_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cleric_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cleric_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },

                // =================== CULTIST =====================
                ["Cultist_Move_S"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Cultist_Move_N"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Cultist_Move_E"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Cultist_Move_W"] = new AnimationConfig { FrameCount = 5, FrameDuration = 5, Loop = true },
                ["Cultist_Move_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Move_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Move_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Move_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Cultist_Idle_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Idle_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Idle_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Idle_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Idle_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Idle_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Idle_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Idle_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Cultist_Attack_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Attack_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Attack_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Attack_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Attack_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Attack_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Attack_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },
                ["Cultist_Attack_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 5, Loop = false },

                ["Cultist_Death_S"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cultist_Death_N"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cultist_Death_E"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cultist_Death_W"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cultist_Death_NE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cultist_Death_NW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cultist_Death_SE"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },
                ["Cultist_Death_SW"] = new AnimationConfig { FrameCount = 1, FrameDuration = 1800, Loop = true },



            };

        public static AnimationConfig Get(string unitType, AnimationState state, Direction direction)
        {
            string fullKey = $"{unitType}_{state}_{direction}";
            if (_configs.TryGetValue(fullKey, out var config))
                return config;

            string stateKey = $"{unitType}_{state}";
            if (_configs.TryGetValue(stateKey, out config))
                return config;

            return AnimationConfig.Idle;
        }
    }
}
